# Generated by Django 4.2.1 on 2023-05-30 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=250)),
                ('last_name', models.CharField(max_length=250)),
                ('phone', models.CharField(max_length=20, unique=True)),
                ('birthday', models.DateField()),
                ('genre', models.IntegerField(choices=[(0, 'Other'), (1, 'Male'), (2, 'Female')])),
            ],
        ),
    ]
