# Generated by Django 4.2.1 on 2023-05-31 23:19

import apps.users.user_profile.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0004_alter_userprofile_birthday_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='profile_image',
            field=models.ImageField(null=True, upload_to=apps.users.user_profile.models.upload_picture_to, verbose_name='profile_image'),
        ),
    ]
